version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - REDIS_HOST=redis
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - CELERY_BROKER=redis://redis:6379/0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - db
      - redis

  db:
    build:
      context: .
      dockerfile: pg-Dockerfile
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - REDIS_HOST=redis
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - CELERY_BROKER=redis://redis:6379/0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
  
  redis:
    image: "redis:alpine"
    container_name: 'games_app_redis'
    ports:
      - 6379:6379
    environment:
      - REDIS_HOST=redis
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - CELERY_BROKER=redis://redis:6379/0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]

  celery:
    build: .
    command: celery -A games_ecommerce worker -l info
    volumes:
      - .:/code
    environment:
      - REDIS_HOST=redis
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - CELERY_BROKER=redis://redis:6379/0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
    command: celery -A games_ecommerce beat -l info
    volumes:
      - .:/code
    environment:
      - REDIS_HOST=redis
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - CELERY_BROKER=redis://redis:6379/0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - web
      - redis

volumes:
  postgres_data:
