version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
    entrypoint: ./scripts/entrypoint.sh
    container_name: 'games_app_web'

  db:
    build:
      context: .
      dockerfile: pg-Dockerfile
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    container_name: 'games_app_db'

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env.dev
    container_name: 'games_app_redis'

  celery:
    build: .
    command: celery -A games_ecommerce worker -l INFO
    volumes:
      - .:/code
    env_file:
      - .env.dev
    depends_on:
      - web
      - redis
    container_name: 'games_app_celery'

  celery-beat:
    build: .
    command: celery -A games_ecommerce beat -l INFO
    volumes:
      - .:/code
    env_file:
      - .env.dev
    depends_on:
      - web
      - redis
    container_name: 'games_app_celery_beat'

volumes:
  postgres_data:
