version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn games_ecommerce.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - redis
    container_name: 'games_app_web'

  db:
    build:
      context: .
      dockerfile: pg-Dockerfile
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    container_name: 'games_app_db'
  
  redis:
    image: "redis:alpine"
    container_name: 'games_app_redis'
    ports:
      - 6379:6379
    env_file:
      - .env
    container_name: 'games_app_redis'

  celery:
    build: .
    command: celery -A games_ecommerce worker -l info --uid=nobody --gid=nogroup
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - web
      - redis
    container_name: 'games_app_celery'

  celery-beat:
    build: .
    command: celery -A games_ecommerce beat -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - web
      - redis
    container_name: 'games_app_celery_beat'

volumes:
  postgres_data:
