name: Games ecommerce

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install pipenv==2018.11.26
        pipenv install --system

    - name: Run the tests
      run: |
        python manage.py test
