name: Games ecommerce CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          pip install pipenv==2018.11.26
          pipenv install --system

      - name: Run the tests
        env:
          DATABASE_URL: 'postgres://postgres:@localhost:${{ job.services.postgres.ports[5432] }}/postgres'
        run: |
          python manage.py test
