name: Games ecommerce CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: games_ecommerce
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: psycopg2 prerequisites
        run: sudo apt-get install python-dev libpq-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: 127.0.0.1
        run: python manage.py migrate

      - name: Run the tests
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: 127.0.0.1
        run: |
          python manage.py test
