name: Games ecommerce

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
        with:
          python-version: 3.7

    - name: Install dependencies
      run: |
        pip install Django==3.0.*

    - name: Run the tests
      run: |
        python runtests.py
